#int
a = 12
print("integer value: ",a)          #integer value: 12
print("Type is: ", type(a) ,"\n")   #Type is: <class int 'int'>


#float
c = 3.09
print("float value: ",c)           #float value: 3.09
print("Type is: ", type(c), "\n")  #Type is: <class 'float'>

#complex
b = 3 + 5j
print("complex value: ", b)        #complex value: (3+5j)
print("Type is: ", type(b), "\n")  #Type is: <class 'complex'>